DROP TABLE IF EXISTS status CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS public.status (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
	deleted_at TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT NULL,
	created_by UUID,
	updated_by UUID,
	name VARCHAR(20) NOT NULL,
	description VARCHAR (255),
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	order_no smallint DEFAULT 0,
	UNIQUE(name)
);
