// Code generated by sqlc. DO NOT EDIT.

package schema

import (
	"fmt"
)

type AddressTypeEnum string

const (
	AddressTypeEnumDefault  AddressTypeEnum = "default"
	AddressTypeEnumShipping AddressTypeEnum = "shipping"
	AddressTypeEnumInvoice  AddressTypeEnum = "invoice"
)

func (e *AddressTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddressTypeEnum(s)
	case string:
		*e = AddressTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AddressTypeEnum: %T", src)
	}
	return nil
}

type Contact struct {
	ContactID       string  `json:"contact_id"`
	FirstName       string  `json:"first_name"`
	LastName        string  `json:"last_name"`
	BusinessName    string  `json:"business_name"`
	JobTitle        string  `json:"job_title"`
	LocationGroupID *string `json:"location_group_id"`
	Image           *string `json:"image"`
	Description     *string `json:"description"`
	ContactGroupID  int     `json:"contact_group_id"`
}

type ContactGroup struct {
	ContactGroupName string `json:"contact_group_name"`
	IsActive         bool   `json:"is_active"`
	ContactGroupID   int    `json:"contact_group_id"`
	ContactTypeID    int    `json:"contact_type_id"`
}

type ContactType struct {
	ContactTypeName string `json:"contact_type_name"`
	IsActive        bool   `json:"is_active"`
	IsLocationGroup bool   `json:"is_location_group"`
	ContactTypeID   int    `json:"contact_type_id"`
}

type ContactsAddress struct {
	ContactsAddressID string          `json:"contacts_address_id"`
	ContactID         string          `json:"contact_id"`
	Address           *string         `json:"address"`
	Zip               *string         `json:"zip"`
	City              *string         `json:"city"`
	Country           *string         `json:"country"`
	Mobile            *string         `json:"mobile"`
	Telephone         *string         `json:"telephone"`
	Email             *string         `json:"email"`
	Website           *string         `json:"website"`
	IsActive          bool            `json:"is_active"`
	AddressType       AddressTypeEnum `json:"address_type"`
}
